spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/parking_prod
    username: parking
    password: password1234
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: redis
      port: 6379
      database: 1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false