spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_dev
    username: parking
    password: password1234
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true